import { Container } from "components";
import Head from "next/head";
import React from "react";
import Header from "../../Header";

interface Props {
  children?: React.ReactNode;
}

const AuthorizedLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Electronics Shop</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Container>
        <Header />
        <main>
          <p>authorized layout</p>
          {children}
        </main>
        <footer>footer</footer>
      </Container>
    </>
  );
};
export default AuthorizedLayout;
