import Header from 'modules/Header'
import Head from 'next/head'
import React from 'react'
import Main from '../modules/Main'

const Home = () => {
	return (
		<>
			<Head>
				<title>Electronics Shop</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<Header />
			<main>
				<Main />
			</main>
			<footer>Footer</footer>
		</>
	)
}

export default Home
