import { Container } from "components";
import Header from "modules/Header";
import Head from "next/head";
import React from "react";

interface Props {
  children?: React.ReactNode;
}
const Layout = ({ children }: Props) => (
  <>
    <Head>
      <title>Electronics Shop</title>
      <meta name='description' content='Generated by create next app' />
    </Head>
    <Container>
      <Header />
      <main>{children}</main>
      <footer>Footer</footer>
    </Container>
  </>
);

export default Layout;
