import { Container } from "components";
import Footer from "modules/Footer";
import Header from "modules/Header";
import Head from "next/head";
import React from "react";

interface Props {
  children?: React.ReactNode;
}
const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Electronics Shop</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Container maxWidth={false} disableGutters={true}>
        <Header />
        <main>{children}</main>
        <Footer />
      </Container>
    </>
  );
};

export default Layout;
