import { Container } from "components";
import Header from "modules/Header";
import Head from "next/head";
import React from "react";
import useDeviceType from "utils/hooks/useDeviceType";

interface Props {
  children?: React.ReactNode;
}
const Layout = ({ children }: Props) => {
  const { isDesktop } = useDeviceType();
  return (
    <>
      <Head>
        <title>Electronics Shop</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Container disableGutters={true}>
        <Header />
        <main>{children}</main>
        <footer>Footer</footer>
      </Container>
    </>
  );
};

export default Layout;
